# Generated by Django 4.0.4 on 2022-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('symbol', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
