# Generated by Django 4.0.4 on 2022-05-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProductTypes',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date_from', models.DateField(blank=True)),
                ('service_date_to', models.DateField(blank=True)),
                ('due_date', models.DateField(blank=True)),
                ('number', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('vat_rate', models.FloatField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updtate_at', models.DateTimeField(auto_now=True)),
                ('billed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billed_to_invoices', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.fiatcurrency')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_invoices', to='companies.company')),
                ('items', models.ManyToManyField(to='invoices.invoiceitems')),
                ('products_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoiceproducttypes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicestatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
