# Generated by Django 4.0.4 on 2022-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='products_type',
            new_name='product_type',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, to='invoices.invoiceitems'),
        ),
    ]
