# Generated by Django 4.0.4 on 2022-05-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_products_type_invoice_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
