# Generated by Django 4.0.4 on 2022-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
