# Generated by Django 4.0.4 on 2022-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoiceitems_total_alter_invoiceitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
