# Generated by Django 4.0.4 on 2022-06-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=100)),
                ('address_post_code', models.CharField(max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=255)),
                ('tax_number', models.CharField(max_length=255)),
                ('founded_on', models.DateField(null=True)),
                ('test_fied', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTypes',
            fields=[
                ('company_type_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
