# Generated by Django 4.0.4 on 2022-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
